# Generated by Django 5.2.9 on 2026-08-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_calculationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='client_logo',
            field=models.ImageField(blank=True, null=True, upload_to='client_logos/', verbose_name='Client Logo'),
        ),
    ]
