# Generated by Django 5.2.9 on 2026-08-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_client_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationjob',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/', verbose_name='Screenshot'),
        ),
    ]
