# Generated by Django 5.2.9 on 2026-09-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_calculationjob_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationjob',
            name='verification_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/verification/', verbose_name='Verification Screenshot'),
        ),
    ]
