# Generated by Django 5.2.9 on 2026-09-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_calculationjob_verification_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationjob',
            name='note_de_calcul',
            field=models.FileField(blank=True, null=True, upload_to='notes_de_calcul/', verbose_name='Note de Calcul'),
        ),
    ]
