# Generated by Django 5.2.9 on 2026-09-28 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_calculationjob_note_de_calcul'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationjob',
            name='credits_consumed',
            field=models.IntegerField(default=1, verbose_name='Credits Consumed'),
        ),
        migrations.AlterField(
            model_name='calculationjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='BASIC', max_length=20, verbose_name='Tier')),
                ('monthly_quota', models.IntegerField(default=50, verbose_name='Monthly Quota')),
                ('used_quota', models.IntegerField(default=0, verbose_name='Used Quota')),
                ('billing_cycle_reset', models.DateField(blank=True, null=True, verbose_name='Billing Cycle Reset')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Client Subscription',
                'verbose_name_plural': 'Client Subscriptions',
            },
        ),
    ]
