# Generated by Django 5.2.9 on 2026-06-02 09:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_alter_antennaequipment_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('commune_insee', models.CharField(db_index=True, max_length=5)),
                ('building_type', models.CharField(max_length=2)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('department_code', models.CharField(db_index=True, max_length=3)),
                ('data_source', models.CharField(default='etalab_cadastre', max_length=20)),
                ('last_import', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'indexes': [models.Index(fields=['department_code', 'commune_insee'], name='geodata_bui_departm_e78e7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CadastreUpdateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=3)),
                ('data_type', models.CharField(max_length=20)),
                ('last_update', models.DateTimeField()),
                ('record_count', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('data_version', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Cadastre Update Status',
                'verbose_name_plural': 'Cadastre Update Statuses',
                'unique_together': {('department_code', 'data_type')},
            },
        ),
    ]
