# Generated by Django 5.2.9 on 2026-06-04 15:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0005_building_cadastreupdatestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_code', models.CharField(db_index=True, max_length=3)),
                ('commune_insee', models.CharField(db_index=True, max_length=5)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('building_count', models.IntegerField(default=1)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Building Block',
                'verbose_name_plural': 'Building Blocks',
                'indexes': [models.Index(fields=['department_code', 'commune_insee'], name='geodata_bui_departm_02a6a9_idx')],
            },
        ),
    ]
