# Generated by Django 5.2.9 on 2026-06-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0006_buildingblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraindocumentation',
            name='local_document_urls',
            field=models.TextField(blank=True, default='', help_text='Comma-separated local paths/URLs for the downloaded documents', verbose_name='Local Document URLs'),
        ),
    ]
