# Generated by Django 5.2.9 on 2026-06-11 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0008_antennaequipment_is_deleted_antennaequipmenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeightCalculationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=255, verbose_name='Nom du demandeur')),
                ('requester_email', models.EmailField(max_length=254, verbose_name='Email du demandeur')),
                ('requester_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone')),
                ('requested_building_height', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Hauteur bâtiment demandée (m)')),
                ('mast_height', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Hauteur du mât (m)')),
                ('montage_type', models.CharField(max_length=50, verbose_name='Type de montage')),
                ('terrain_type', models.CharField(blank=True, default='', max_length=10, verbose_name='Type de terrain')),
                ('region', models.IntegerField(blank=True, null=True, verbose_name='Région')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description / justification')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_height_requests', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('completed_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='geodata.antennaequipment', verbose_name='Équipement créé')),
                ('requester_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='height_requests', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur demandeur')),
            ],
            options={
                'verbose_name': 'Demande de calcul de hauteur',
                'verbose_name_plural': 'Demandes de calcul de hauteur',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email du destinataire')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='Lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('notification_type', models.CharField(choices=[('request_received', 'Demande reçue'), ('request_in_progress', 'Demande en cours'), ('request_completed', 'Demande terminée'), ('request_rejected', 'Demande rejetée'), ('info', 'Information')], default='info', max_length=30, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur destinataire')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='geodata.heightcalculationrequest', verbose_name='Demande associée')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
