# Generated by Django 5.2.9 on 2026-06-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0009_heightcalculationrequest_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precalculated_building_heights', models.JSONField(default=list, help_text='List of building heights (m) that have pre-computed structural studies, e.g. [10, 15, 20, 25, 30, 35, 40, 45]', verbose_name='Precalculated Building Heights')),
                ('recommended_mast_heights', models.JSONField(default=list, help_text='Recommended mast heights (m) shown as quick-select buttons, e.g. [3, 4]', verbose_name='Recommended Mast Heights')),
                ('fh_weight_options', models.JSONField(default=list, help_text='FH equipment weight options (kg) for the dropdown, e.g. [20, 25, 30, ...]', verbose_name='FH Weight Options')),
                ('standard_montages', models.JSONField(default=list, help_text='Standard montage definitions. Each entry: {"id": "A1", "name": "Montage A1", "abbreviation": "A1a / A1b", "ant4g": {"height": 2100, "width": 470, "thickness": 210, "weight": 45}, "ant5g": {"height": 1010, "width": 500, "thickness": 250, "weight": 50}}', verbose_name='Standard Montages')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Catalogue Configuration',
                'verbose_name_plural': 'Catalogue Configuration',
            },
        ),
    ]
