# Generated by Django 5.2.9 on 2026-07-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0010_catalogue_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrainloadcalculation',
            name='bras_de_deport',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section Bras de déport'),
        ),
        migrations.AddField(
            model_name='terrainloadcalculation',
            name='mat_secondaire',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section Mat antenne 5G'),
        ),
        migrations.AddField(
            model_name='terrainloadcalculation',
            name='plot_metallique',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section Plot Métallique'),
        ),
    ]
