# Generated by Django 5.2.9 on 2026-07-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0011_terrainloadcalculation_bras_de_deport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueconfig',
            name='real_world_references',
            field=models.JSONField(default=list, help_text='List of real world references (e.g. equipment setups)'),
        ),
    ]
