# Generated by Django 5.2.9 on 2026-07-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0012_catalogueconfig_real_world_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='antennaequipment',
            name='reference_4g',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Référence 4G'),
        ),
        migrations.AddField(
            model_name='antennaequipment',
            name='reference_5g',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Référence 5G'),
        ),
    ]
