# Generated by Django 5.2.9 on 2026-07-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0013_antennaequipment_reference_4g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueconfig',
            name='coffret_references',
            field=models.JSONField(default=list, help_text='List of coffret references (e.g. HTTA, hybride, etc.)', verbose_name='Coffret References'),
        ),
    ]
