# Generated by Django 5.2.9 on 2026-09-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0014_catalogueconfig_coffret_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueconfig',
            name='fh_references',
            field=models.JSONField(default=list, help_text='List of FH equipment references with diameter and weight', verbose_name='FH References'),
        ),
    ]
