# Generated by Django 5.2.9 on 2026-09-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0015_catalogueconfig_fh_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueconfig',
            name='rru_references',
            field=models.JSONField(default=list, help_text='List of RRU/RRH equipment references with vendor', verbose_name='RRU References'),
        ),
        migrations.AddField(
            model_name='catalogueconfig',
            name='td_references',
            field=models.JSONField(default=list, help_text='List of TD equipment references with weight and dimensions', verbose_name='TD References'),
        ),
    ]
