# Generated by Django 5.2.9 on 2026-09-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0016_catalogueconfig_rru_references_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueconfig',
            name='rrh_references',
            field=models.JSONField(default=list, help_text='List of RRH equipment references with vendor', verbose_name='RRH References'),
        ),
    ]
