# Generated by Django 5.2.9 on 2026-09-22 07:44

import django.core.management
from django.db import migrations


def load_catalogue_config(apps, schema_editor):
    django.core.management.call_command('loaddata', 'geodata/fixtures/catalogue_config.json')

class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0017_catalogueconfig_rrh_references'),
    ]

    operations = [
        migrations.RunPython(load_catalogue_config),
    ]
